### ISSUE TITLE
generalize namespace, to make room for other features

### ISSUE THREAD

**Issue by chadmiller** [cforlando/bike-orlando-android#19]
I think it's better to have less-specific Java package name before launch. I think the bike app should be an Activity of a more general transportation app, of which, a bike map is a part. If lots of people keep it installed we can gather aggregate data and the usefulness of future features is compounded. A bike-map app is currently too specific for many people to install and use for very long. 

We can add more activities, Services, or add a more general interface later. I'm sure we all have ideas, so it's not quite YAGNI. Let's have a less-specific Java package name before launch. 

I'm no marketing person, but if we need a name for something attractive to all users, bikers and drivers and walkers, my suggestion is "Orlando Cityzen".  A few shades of meaning there.

**Comment by ToxicBakery** [comment]
Resolved
