### ISSUE TITLE
speak warning of red-light-cameras

### ISSUE THREAD

**Issue by chadmiller** [cforlando/bike-orlando-android#23]
A gravy feature to get people to selfishly keep app on device, so we get to ask them to report info back up.

Speak a warning about red-light cameras when approaching an intersection with one, at speed above 30MPH.

**Comment by ToxicBakery** [comment]
So Waze and Google Maps provide this inherently now. Not sure its really a sensible feature given the inability for apps to provide navigation without rolling it themselves which we do not have the infrastructure for obviously.
