### ISSUE TITLE
Question about project

### ISSUE THREAD

**Issue by mikez23** [cforlando/bike-orlando-android#60]
What is the state of this project ? I was working lon adding Lynx Bus Stops, till I got sick. I was sick two months. I have code and was getting close to be able to display bus stops.What should I do with it?

**Comment by ToxicBakery** [comment]
Yeah, you should throw it in. Just make sure you branch from the latest development branch before you start on it.

**Comment by mikez23** [comment]
Ok I will do that then.
               Thanks
                    Mike
